'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class AgenciaSendingPueblo
        Public Property Id As Integer
        Public Property CODP_CODIGO As String
        Public Property DELE_CODIGO As String
        Public Property DELE_CODIGO_1 As String
        Public Property ZONA_CODIGO As String
        Public Property POBL_NOMBRE As String
        Public Property PAIS_CODIGO As String
    
    End Class

End Namespace
