'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class AgenciasTransporte
        Public Property Numero As Integer
        Public Property Empresa As String
        Public Property Nombre As String
        Public Property Ruta As String
        Public Property Identificador As String
        Public Property PrefijoCodigoBarras As String
        Public Property Usuario As String
        Public Property FechaModificacion As Date
        Public Property CuentaReembolsos As String
    
        Public Overridable Property Empresas As Empresas
        Public Overridable Property EnviosAgencia As ICollection(Of EnviosAgencia) = New HashSet(Of EnviosAgencia)
        Public Overridable Property Rutas As Rutas
    
    End Class

End Namespace
