'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class CabAlquileres
        Public Property Empresa As String
        Public Property Número As Integer
        Public Property Cliente As String
        Public Property Contacto As String
        Public Property Producto As String
        Public Property Inmovilizado As String
        Public Property Cuotas As Nullable(Of Integer)
        Public Property FechaEntrega As Nullable(Of Date)
        Public Property FechaSeñal As Nullable(Of Date)
        Public Property ImporteSeñal As Nullable(Of Decimal)
        Public Property NumeroSerie As String
        Public Property NombreProducto As String
        Public Property Familia As String
        Public Property SeñalComisiona As Nullable(Of Boolean)
        Public Property Indemnización As Nullable(Of Decimal)
        Public Property Importe As Nullable(Of Decimal)
        Public Property CabPedidoVta As Nullable(Of Integer)
        Public Property RutaContrato As String
        Public Property Usuario As String
        Public Property FechaModificación As Date
        Public Property Comentarios As String
    
        Public Overridable Property Productos As Productos
        Public Overridable Property Inmovilizados As Inmovilizados
        Public Overridable Property CabPedidoVta1 As CabPedidoVta
        Public Overridable Property Clientes As Clientes
    
    End Class

End Namespace
