'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class CabFacturaVta
        Public Property Empresa As String
        Public Property Número As String
        Public Property Fecha As Date
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property Forma_Pago As String
        Public Property PlazosPago As String
        Public Property IVA As String
        Public Property Vendedor As String
        Public Property CCC As String
        Public Property Espejo As String
        Public Property Primer_Vencimiento As Nullable(Of Date)
        Public Property Serie As String
        Public Property Origen As String
        Public Property ContactoCobro As String
        Public Property NoComisiona As Decimal
        Public Property Operador As String
        Public Property Cadena As String
        Public Property EstadoCliente As Short
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property LinPedidoVta As ICollection(Of LinPedidoVta) = New HashSet(Of LinPedidoVta)
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property CCC1 As CCC
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Empresas As Empresas
        Public Overridable Property Empresas1 As Empresas
    
    End Class

End Namespace
