'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class CabPedidoVta
        Public Property Empresa As String
        Public Property Número As Integer
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property Fecha As Nullable(Of Date)
        Public Property Forma_Pago As String
        Public Property PlazosPago As String
        Public Property Primer_Vencimiento As Nullable(Of Date)
        Public Property IVA As String
        Public Property Vendedor As String
        Public Property Comentarios As String
        Public Property ComentarioPicking As String
        Public Property Periodo_Facturacion As String
        Public Property Ruta As String
        Public Property Serie As String
        Public Property CCC As String
        Public Property Origen As String
        Public Property Agrupada As Boolean
        Public Property MotivoDevolución As String
        Public Property ContactoCobro As String
        Public Property NoComisiona As Decimal
        Public Property NotaEntrega As Boolean
        Public Property vtoBuenoPlazosPago As Boolean
        Public Property Operador As String
        Public Property FijarPrimerVto As Boolean
        Public Property MantenerJunto As Boolean
        Public Property ServirJunto As Boolean
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
        Public Property RowVersion As Byte()
    
        Public Overridable Property CabAlquileres As ICollection(Of CabAlquileres) = New HashSet(Of CabAlquileres)
        Public Overridable Property LinPedidoVta As ICollection(Of LinPedidoVta) = New HashSet(Of LinPedidoVta)
        Public Overridable Property Clientes As Clientes
    
    End Class

End Namespace
