'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class CCC
        Public Property Empresa As String
        Public Property Cliente As String
        Public Property Contacto As String
        Public Property Número As String
        Public Property Pais As String
        Public Property DC_IBAN As String
        Public Property Entidad As String
        Public Property Oficina As String
        Public Property DC As String
        Public Property Nº_Cuenta As String
        Public Property Estado As Short
        Public Property TipoMandato As Nullable(Of Short)
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
        Public Property BIC As String
        Public Property FechaMandato As Nullable(Of Date)
        Public Property Secuencia As String
    
        Public Overridable Property CabFacturaVta As ICollection(Of CabFacturaVta) = New HashSet(Of CabFacturaVta)
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Clientes1 As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Empresas As Empresas
        Public Overridable Property EstadosCCC As EstadosCCC
        Public Overridable Property ExtractoCliente As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
    
    End Class

End Namespace
