'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Clientes
        Public Property Empresa As String
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property ClientePrincipal As Boolean
        Public Property Nombre As String
        Public Property Dirección As String
        Public Property Población As String
        Public Property Teléfono As String
        Public Property Fax As String
        Public Property Vendedor As String
        Public Property Comentarios As String
        Public Property CodPostal As String
        Public Property CIF_NIF As String
        Public Property Provincia As String
        Public Property Estado As Nullable(Of Short)
        Public Property IVA As String
        Public Property Grupo As String
        Public Property PeriodoFacturación As String
        Public Property CCC As String
        Public Property Ruta As String
        Public Property NºCopiasAlbarán As Byte
        Public Property NºCopiasFactura As Byte
        Public Property ComentarioRuta As String
        Public Property ComentarioPicking As String
        Public Property GeneraBonificación As Boolean
        Public Property RecargoPvp As Nullable(Of Decimal)
        Public Property Web As String
        Public Property BloquearPlazosPago As Boolean
        Public Property AvisarAntesCobro As Boolean
        Public Property ContactoDefecto As String
        Public Property ContactoCobro As String
        Public Property ContactoBonificacion As String
        Public Property AlbaranValorado As Boolean
        Public Property Cadena As String
        Public Property NoComisiona As Decimal
        Public Property Operador As String
        Public Property DiasEnServir As String
        Public Property ServirJunto As Boolean
        Public Property MantenerJunto As Boolean
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property CabAlquileres As ICollection(Of CabAlquileres) = New HashSet(Of CabAlquileres)
        Public Overridable Property CabFacturaVta As ICollection(Of CabFacturaVta) = New HashSet(Of CabFacturaVta)
        Public Overridable Property CCC1 As ICollection(Of CCC) = New HashSet(Of CCC)
        Public Overridable Property CCC2 As CCC
        Public Overridable Property Clientes1 As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Clientes2 As Clientes
        Public Overridable Property Clientes11 As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Clientes3 As Clientes
        Public Overridable Property Clientes12 As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Clientes4 As Clientes
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property LinPedidoVta As ICollection(Of LinPedidoVta) = New HashSet(Of LinPedidoVta)
        Public Overridable Property Empresas As Empresas
        Public Overridable Property ExtractoCliente As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
        Public Overridable Property PersonasContactoCliente As ICollection(Of PersonasContactoCliente) = New HashSet(Of PersonasContactoCliente)
        Public Overridable Property PersonasContactoCliente1 As ICollection(Of PersonasContactoCliente) = New HashSet(Of PersonasContactoCliente)
        Public Overridable Property SeguimientoCliente As ICollection(Of SeguimientoCliente) = New HashSet(Of SeguimientoCliente)
        Public Overridable Property CabPedidoVta As ICollection(Of CabPedidoVta) = New HashSet(Of CabPedidoVta)
        Public Overridable Property EnviosAgencia As ICollection(Of EnviosAgencia) = New HashSet(Of EnviosAgencia)
    
    End Class

End Namespace
