'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Contabilidad
        Public Property Empresa As String
        Public Property Nº_Orden As Integer
        Public Property TipoApunte As String
        Public Property Nº_Cuenta As String
        Public Property Concepto As String
        Public Property Debe As Decimal
        Public Property Haber As Decimal
        Public Property Fecha As Date
        Public Property Nº_Documento As String
        Public Property Asiento As Nullable(Of Integer)
        Public Property Asiento_Automático As Boolean
        Public Property AsientoSecuencial As Nullable(Of Integer)
        Public Property Delegación As String
        Public Property FormaVenta As String
        Public Property Diario As String
        Public Property Origen As String
        Public Property Punteado As Boolean
        Public Property CentroCoste As String
        Public Property Departamento As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
    End Class

End Namespace
