'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Empresas
        Public Property Número As String
        Public Property Nombre As String
        Public Property NIF As String
        Public Property Sufijo As String
        Public Property MostrarMenú As Boolean
        Public Property IVA_por_defecto As String
        Public Property CtaDtoCliente As String
        Public Property CtaDescuentoVta As String
        Public Property CtaDtoPPVta As String
        Public Property CtaDtoProveedor As String
        Public Property CtaDescuentoCmp As String
        Public Property CtaDtoPPCmp As String
        Public Property DelegaciónVarios As String
        Public Property FormaVentaVarios As String
        Public Property CtaCaja As String
        Public Property CtaDescuadre As String
        Public Property LongitudCuenta As Nullable(Of Byte)
        Public Property FormaPagoTalón As String
        Public Property FormaPagoEfectivo As String
        Public Property FormaPagoTarjeta As String
        Public Property FormaPagoPagaré As String
        Public Property PlazosPagoDefecto As String
        Public Property VendedorVarios As String
        Public Property Dirección As String
        Public Property Dirección2 As String
        Public Property Teléfono As String
        Public Property Fax As String
        Public Property CodPostal As String
        Public Property Población As String
        Public Property Provincia As String
        Public Property Texto As String
        Public Property Logotipo As String
        Public Property TipoIvaDefecto As String
        Public Property GeneraBonificaciónDefecto As Boolean
        Public Property VigenciaBonificación As Byte
        Public Property CtaRegularización As String
        Public Property CtaRemanente As String
        Public Property CtaDiferenciasNegativasEjerciciosAnteriores As String
        Public Property CtaAPagarIVA As String
        Public Property CtaACompensarIVA As String
        Public Property TipoIvaDefectoSoportado As String
        Public Property ProductoRegularizaciones As String
        Public Property ProductoReparacion As String
        Public Property Email As String
        Public Property Web As String
        Public Property EmpresaDatafono As String
        Public Property EmpresaCurso As Boolean
        Public Property EstadoReembolsado As String
        Public Property ProveedorCostes As String
        Public Property ctaDiferenciasEnCompras As String
        Public Property UltAsientoContable As Integer
        Public Property ProveedorIRPF As String
        Public Property ContactoProveedorIRPF As String
        Public Property PorcentajeFacturadoNoEntregadoParaPedidoCmpAuto As Decimal
        Public Property TextoFactura As String
        Public Property StockAntiguo As Integer
        Public Property EstadoProductoRegalo As Nullable(Of Integer)
        Public Property InformeAlbaran As String
        Public Property InformeFactura As String
        Public Property InformePedidoCmp As String
        Public Property InformeCartaPagare As String
        Public Property InformeCartaPagareManual As String
        Public Property ImpresoraPagare As String
        Public Property OcultarB As Boolean
        Public Property MostrarOperador As Boolean
        Public Property MaxPickingListado As Nullable(Of Integer)
        Public Property MaxPickingPorListar As Nullable(Of Integer)
        Public Property InformeFacturaConMembrete As String
        Public Property VerFormaVentaCng As Boolean
        Public Property PreciosRenting36 As Nullable(Of Decimal)
        Public Property PreciosRenting48 As Nullable(Of Decimal)
        Public Property PreciosRentingImporte As Nullable(Of Decimal)
        Public Property PorcentajeVR36 As Nullable(Of Decimal)
        Public Property PorcentajeVR48 As Nullable(Of Decimal)
        Public Property PorcentajeRentingProductos As Nullable(Of Decimal)
        Public Property PorcentajeRentingServicios As Nullable(Of Decimal)
        Public Property EnviarCorreoProductoNuevo As Boolean
        Public Property ctaTrabajosRealizados As String
        Public Property FechaPicking As Nullable(Of Date)
        Public Property BloquearTraspasoRuta As Boolean
        Public Property RutaImpagado As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property CabFacturaVta As ICollection(Of CabFacturaVta) = New HashSet(Of CabFacturaVta)
        Public Overridable Property CabFacturaVta1 As ICollection(Of CabFacturaVta) = New HashSet(Of CabFacturaVta)
        Public Overridable Property CCC As ICollection(Of CCC) = New HashSet(Of CCC)
        Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Empresas1 As ICollection(Of Empresas) = New HashSet(Of Empresas)
        Public Overridable Property Empresas2 As Empresas
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property ExtractoInmovilizado As ICollection(Of ExtractoInmovilizado) = New HashSet(Of ExtractoInmovilizado)
        Public Overridable Property Inmovilizados As ICollection(Of Inmovilizados) = New HashSet(Of Inmovilizados)
        Public Overridable Property LinPedidoCmp As ICollection(Of LinPedidoCmp) = New HashSet(Of LinPedidoCmp)
        Public Overridable Property LinPedidoVta As ICollection(Of LinPedidoVta) = New HashSet(Of LinPedidoVta)
        Public Overridable Property Productos As ICollection(Of Productos) = New HashSet(Of Productos)
        Public Overridable Property Vendedores1 As ICollection(Of Vendedores) = New HashSet(Of Vendedores)
        Public Overridable Property Remesas As ICollection(Of Remesas) = New HashSet(Of Remesas)
        Public Overridable Property ExtractoCliente As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
        Public Overridable Property ExtractoCliente1 As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
        Public Overridable Property PersonasContactoCliente As ICollection(Of PersonasContactoCliente) = New HashSet(Of PersonasContactoCliente)
        Public Overridable Property SeguimientoCliente As ICollection(Of SeguimientoCliente) = New HashSet(Of SeguimientoCliente)
        Public Overridable Property PlanesVentajas As ICollection(Of PlanesVentajas) = New HashSet(Of PlanesVentajas)
        Public Overridable Property ExtractoRuta As ICollection(Of ExtractoRuta) = New HashSet(Of ExtractoRuta)
        Public Overridable Property AgenciasTransporte As ICollection(Of AgenciasTransporte) = New HashSet(Of AgenciasTransporte)
        Public Overridable Property EnviosAgencia As ICollection(Of EnviosAgencia) = New HashSet(Of EnviosAgencia)
        Public Overridable Property Rutas As ICollection(Of Rutas) = New HashSet(Of Rutas)
        Public Overridable Property MultiUsuarios As ICollection(Of MultiUsuarios) = New HashSet(Of MultiUsuarios)
        Public Overridable Property EtiquetasPicking As ICollection(Of EtiquetasPicking) = New HashSet(Of EtiquetasPicking)
    
    End Class

End Namespace
