'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class EnviosAgencia
        Public Property Numero As Integer
        Public Property Empresa As String
        Public Property Agencia As Integer
        Public Property Cliente As String
        Public Property Contacto As String
        Public Property Pedido As Nullable(Of Integer)
        Public Property Estado As Short
        Public Property Fecha As Date
        Public Property Servicio As Byte
        Public Property Horario As Byte
        Public Property Bultos As Byte
        Public Property Retorno As Byte
        Public Property Nombre As String
        Public Property Direccion As String
        Public Property CodPostal As String
        Public Property Poblacion As String
        Public Property Provincia As String
        Public Property Telefono As String
        Public Property Movil As String
        Public Property Email As String
        Public Property Observaciones As String
        Public Property Atencion As String
        Public Property Reembolso As Decimal
        Public Property CodigoBarras As String
        Public Property NombrePlaza As String
        Public Property Nemonico As String
        Public Property TelefonoPlaza As String
        Public Property EmailPlaza As String
        Public Property Vendedor As String
        Public Property FechaFactura As Nullable(Of Date)
        Public Property ImporteGasto As Decimal
        Public Property Usuario As String
        Public Property FechaModificacion As Date
        Public Property FechaPagoReembolso As Nullable(Of Date)
        Public Property FechaRetornoRecibido As Nullable(Of Date)
        Public Property Pais As Integer
        Public Property FechaEntrega As Nullable(Of Date)
        Public Property RowVersion As Byte()
        Public Property ImporteAsegurado As Decimal
        Public Property Peso As Decimal

        Public Overridable Property Clientes As Clientes
        Public Overridable Property Empresas As Empresas
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property AgenciasTransporte As AgenciasTransporte
        Public Overridable Property EnviosHistoria As ICollection(Of EnviosHistoria) = New HashSet(Of EnviosHistoria)
    
    End Class

End Namespace
