'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class ExtractoInmovilizado
        Public Property Empresa As String
        Public Property NºOrden As Integer
        Public Property TipoApunte As Byte
        Public Property Grupo As String
        Public Property Número As String
        Public Property Concepto As String
        Public Property Fecha As Date
        Public Property NºDocumento As String
        Public Property Importe As Decimal
        Public Property ImportePdte As Decimal
        Public Property Delegación As String
        Public Property CentroCoste As String
        Public Property LinPedido As Nullable(Of Integer)
        Public Property FechaModificacion As Byte()
        Public Property NºCuota As Integer
        Public Property Asiento As Nullable(Of Integer)
        Public Property Estado As Short
        Public Property Usuario As String
        Public Property FechaCreacion As Date
    
        Public Overridable Property Inmovilizados As Inmovilizados
        Public Overridable Property Empresas As Empresas
    
    End Class

End Namespace
