'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class ExtractoRuta
        Public Property Empresa As String
        Public Property Nº_Orden As Integer
        Public Property Número As String
        Public Property Contacto As String
        Public Property CodPostal As String
        Public Property Fecha As Date
        Public Property Nº_Documento As String
        Public Property Efecto As String
        Public Property Concepto As String
        Public Property Importe As Decimal
        Public Property ImportePdte As Decimal
        Public Property Delegación As String
        Public Property FormaVenta As String
        Public Property Vendedor As String
        Public Property FechaVto As Nullable(Of Date)
        Public Property FormaPago As String
        Public Property Ruta As String
        Public Property Estado As Byte
        Public Property TipoRuta As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property Empresas As Empresas
        Public Overridable Property Vendedores As Vendedores
        Public Overridable Property Rutas As Rutas
    
    End Class

End Namespace
