'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class FamiliasVendedor
        Public Property Id As Integer
        Public Property Empresa As String
        Public Property CodigoPostal As String
        Public Property Vendedor As String
        Public Property Familia As String
        Public Property FechaDesde As Date
        Public Property FechaHasta As Date
        Public Property FechaModificacion As Date
        Public Property Usuario As String
    
        Public Overridable Property Vendedores As Vendedores
    
    End Class

End Namespace
