'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Inmovilizados
        Public Property Empresa As String
        Public Property Número As String
        Public Property Descripción As String
        Public Property Grupo As String
        Public Property Delegación As String
        Public Property CentroCoste As String
        Public Property Amortizable As Boolean
        Public Property Estado As Short
        Public Property FechaModificación As Byte()
        Public Property Usuario As String
        Public Property FechaCreación As Date
    
        Public Overridable Property CabAlquileres As ICollection(Of CabAlquileres) = New HashSet(Of CabAlquileres)
        Public Overridable Property ExtractoInmovilizado As ICollection(Of ExtractoInmovilizado) = New HashSet(Of ExtractoInmovilizado)
        Public Overridable Property Empresas As Empresas
    
    End Class

End Namespace
