'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class LinPedidoCmp
        Public Property Empresa As String
        Public Property Número As Integer
        Public Property NºOrden As Integer
        Public Property NºProveedor As String
        Public Property Contacto As String
        Public Property TipoLínea As String
        Public Property Producto As String
        Public Property Almacén As String
        Public Property FechaRecepción As Nullable(Of Date)
        Public Property Texto As String
        Public Property Cantidad As Nullable(Of Short)
        Public Property Precio As Decimal
        Public Property Bruto As Decimal
        Public Property IVA As String
        Public Property PorcentajeIVA As Decimal
        Public Property PorcentajeRE As Decimal
        Public Property DescuentoProveedor As Decimal
        Public Property DescuentoProducto As Decimal
        Public Property Descuento As Decimal
        Public Property DescuentoPP As Decimal
        Public Property SumaDescuentos As Decimal
        Public Property ImporteDto As Decimal
        Public Property BaseImponible As Decimal
        Public Property ImporteIVA As Decimal
        Public Property ImporteRE As Decimal
        Public Property Total As Decimal
        Public Property AplicarDto As Boolean
        Public Property Delegación As String
        Public Property FormaVenta As String
        Public Property NºAlbarán As Nullable(Of Integer)
        Public Property FechaAlbarán As Nullable(Of Date)
        Public Property NºFactura As String
        Public Property FechaFactura As Nullable(Of Date)
        Public Property Estado As Short
        Public Property Grupo As String
        Public Property Subgrupo As String
        Public Property NºOferta As Nullable(Of Byte)
        Public Property VistoBueno As Boolean
        Public Property Enviado As Boolean
        Public Property Coste As Decimal
        Public Property CentroCoste As String
        Public Property PrecioTarifa As Nullable(Of Decimal)
        Public Property YaFacturado As Boolean
        Public Property Reponer As Boolean
        Public Property Departamento As String
        Public Property C__IRPF As Decimal
        Public Property EstadoProducto As Nullable(Of Integer)
        Public Property NumSerie As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property Empresas As Empresas
    
    End Class

End Namespace
