'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class LinPedidoVta
        Public Property Empresa As String
        Public Property Número As Integer
        Public Property Nº_Orden As Integer
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property TipoLinea As Nullable(Of Byte)
        Public Property Producto As String
        Public Property Almacén As String
        Public Property Fecha_Entrega As Date
        Public Property Texto As String
        Public Property Cantidad As Nullable(Of Short)
        Public Property Precio As Nullable(Of Decimal)
        Public Property IVA As String
        Public Property PorcentajeIVA As Byte
        Public Property PorcentajeRE As Decimal
        Public Property Bruto As Decimal
        Public Property DescuentoCliente As Decimal
        Public Property DescuentoProducto As Decimal
        Public Property Descuento As Decimal
        Public Property DescuentoPP As Decimal
        Public Property SumaDescuentos As Decimal
        Public Property ImporteDto As Decimal
        Public Property Base_Imponible As Decimal
        Public Property ImporteIVA As Decimal
        Public Property ImporteRE As Decimal
        Public Property Total As Decimal
        Public Property Aplicar_Dto As Boolean
        Public Property Delegación As String
        Public Property Forma_Venta As String
        Public Property Nº_Albarán As Nullable(Of Integer)
        Public Property Fecha_Albarán As Nullable(Of Date)
        Public Property Nº_Factura As String
        Public Property Fecha_Factura As Nullable(Of Date)
        Public Property Picking As Nullable(Of Integer)
        Public Property Estado As Short
        Public Property Grupo As String
        Public Property SubGrupo As String
        Public Property NºOferta As Nullable(Of Integer)
        Public Property GeneraBonificación As Boolean
        Public Property Familia As String
        Public Property TipoExclusiva As String
        Public Property YaFacturado As Boolean
        Public Property VtoBueno As Boolean
        Public Property Coste As Decimal
        Public Property BlancoParaBorrar As String
        Public Property Reponer As Boolean
        Public Property PrecioTarifa As Nullable(Of Decimal)
        Public Property Recoger As Integer
        Public Property LineaParcial As Boolean
        Public Property EstadoProducto As Nullable(Of Integer)
        Public Property CentroCoste As String
        Public Property Departamento As String
        Public Property NumSerie As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
        Public Property RowVersion As Byte()
    
        Public Overridable Property CabFacturaVta As CabFacturaVta
        Public Overridable Property CabPedidoVta As CabPedidoVta
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Empresas As Empresas
        Public Overridable Property SubGruposProducto As SubGruposProducto
    
    End Class

End Namespace
