'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class MultiUsuarios
        Public Property Empresa As String
        Public Property Número As Integer
        Public Property Nombre As String
        Public Property Estado As Short
        Public Property Máquina As String
        Public Property FechaUltimaConexion As Nullable(Of Date)
        Public Property Usuario As String
        Public Property FechaModificación As Date
    
        Public Overridable Property Empresas As Empresas
        Public Overridable Property EtiquetasPicking As ICollection(Of EtiquetasPicking) = New HashSet(Of EtiquetasPicking)
    
    End Class

End Namespace
