'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class PersonasContactoCliente
        Public Property Empresa As String
        Public Property NºCliente As String
        Public Property Contacto As String
        Public Property Número As String
        Public Property Nombre As String
        Public Property Cargo As Short
        Public Property Comentarios As String
        Public Property Teléfono As String
        Public Property Fax As String
        Public Property CorreoElectrónico As String
        Public Property EnviarBoletin As Boolean
        Public Property Estado As Short
        Public Property Saludo As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Clientes1 As Clientes
        Public Overridable Property Empresas As Empresas
        Public Overridable Property Cargos As Cargos
    
    End Class

End Namespace
