'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class PlanVentajasCliente
        Public Property Numero As Integer
        Public Property NumeroContrato As Integer
        Public Property Cliente As String
        Public Property Usuario As String
        Public Property FechaModificacion As Date
    
        Public Overridable Property PlanesVentajas As PlanesVentajas
    
    End Class

End Namespace
