'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class PlanesVentajas
        Public Property Numero As Integer
        Public Property Empresa As String
        Public Property FechaInicio As Date
        Public Property FechaFin As Date
        Public Property Importe As Decimal
        Public Property Familia As String
        Public Property Estado As Integer
        Public Property Comentarios As String
        Public Property Usuario As String
        Public Property FechaModificacion As Date
    
        Public Overridable Property Empresas As Empresas
        Public Overridable Property EstadosPlanVentajas As EstadosPlanVentajas
        Public Overridable Property PlanVentajasCliente As ICollection(Of PlanVentajasCliente) = New HashSet(Of PlanVentajasCliente)
    
    End Class

End Namespace
