'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class prdProductosAlquiler
        Public Property Empresa As String
        Public Property Número As String
        Public Property Nombre As String
        Public Property Stock As Integer
        Public Property StockAlquileres As Integer
        Public Property Diferencia As Integer
    
    End Class

End Namespace
