'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class PreContabilidad
        Public Property Empresa As String
        Public Property Nº_Orden As Integer
        Public Property TipoApunte As String
        Public Property TipoCuenta As String
        Public Property Nº_Cuenta As String
        Public Property Nº_Remesa As String
        Public Property Contacto As String
        Public Property Concepto As String
        Public Property Debe As Decimal
        Public Property Haber As Decimal
        Public Property Fecha As Date
        Public Property Nº_Documento As String
        Public Property Efecto As String
        Public Property Asiento As Nullable(Of Integer)
        Public Property Diario As String
        Public Property Asiento_Automático As Boolean
        Public Property IVA_Cliente_Prov As String
        Public Property IVA_Producto As String
        Public Property ImporteIVA As Nullable(Of Decimal)
        Public Property Delegación As String
        Public Property FormaVenta As String
        Public Property FechaVto As Nullable(Of Date)
        Public Property FormaPago As String
        Public Property ImporteApunte As Nullable(Of Decimal)
        Public Property Vendedor As String
        Public Property CCC As String
        Public Property Contrapartida As String
        Public Property Liquidado As Nullable(Of Integer)
        Public Property Ruta As String
        Public Property CajaLiquidada As Boolean
        Public Property NºDocumentoProv As String
        Public Property CentroCoste As String
        Public Property Origen As String
        Public Property Departamento As String
        Public Property TipoRuta As String
        Public Property FechaProveedor As Nullable(Of Date)
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
    End Class

End Namespace
