'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class PrestashopProductos
        Public Property Empresa As String
        Public Property Número As String
        Public Property Nombre As String
        Public Property DescripciónBreve As String
        Public Property Descripción As String
        Public Property PVP_IVA_Incluido As Nullable(Of Decimal)
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
        Public Property VistoBueno As Nullable(Of Boolean)
    
        Public Overridable Property Productos As Productos
    
    End Class

End Namespace
