'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Productos
        Public Property Empresa As String
        Public Property Número As String
        Public Property Nombre As String
        Public Property Grupo As String
        Public Property PVP As Nullable(Of Decimal)
        Public Property IVA_Soportado As String
        Public Property IVA_Repercutido As String
        Public Property Comentarios As String
        Public Property Estado As Nullable(Of Short)
        Public Property CodBarras As String
        Public Property Aplicar_Dto As Boolean
        Public Property SubGrupo As String
        Public Property Tamaño As Nullable(Of Short)
        Public Property UnidadMedida As String
        Public Property Familia As String
        Public Property Foto As String
        Public Property PrecioMedio As Nullable(Of Decimal)
        Public Property Ficticio As Boolean
        Public Property FechaInicio As Nullable(Of Date)
        Public Property FechaFinal As Nullable(Of Date)
        Public Property NumeroSesiones As Nullable(Of Byte)
        Public Property MateriaPrima As Boolean
        Public Property UnidadesPorEtiqueta As Short
        Public Property VariasOpciones As Boolean
        Public Property Ubicar As Boolean
        Public Property ProductoAnterior As String
        Public Property GestionStockManual As Boolean
        Public Property RoturaStockProveedor As Boolean
        Public Property ProductosPorCaja As Integer
        Public Property CantidadMinimaPedido As Integer
        Public Property Revisado As Boolean
        Public Property ComentariosFactura As String
        Public Property NecesitaNumSerie As Boolean
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property Productos1 As ICollection(Of Productos) = New HashSet(Of Productos)
        Public Overridable Property Productos2 As Productos
        Public Overridable Property CabAlquileres As ICollection(Of CabAlquileres) = New HashSet(Of CabAlquileres)
        Public Overridable Property PrestashopProductos As PrestashopProductos
        Public Overridable Property Empresas As Empresas
        Public Overridable Property SubGruposProducto As SubGruposProducto
    
    End Class

End Namespace
