'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Rutas
        Public Property Empresa As String
        Public Property Número As String
        Public Property Descripción As String
        Public Property Activa As Boolean
        Public Property DiaReposicion As Integer
        Public Property Traspasar As String
        Public Property ImporteMinimo As Decimal
        Public Property Copias As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property AgenciasTransporte As ICollection(Of AgenciasTransporte) = New HashSet(Of AgenciasTransporte)
        Public Overridable Property Empresas As Empresas
        Public Overridable Property ExtractoCliente As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
        Public Overridable Property ExtractoRuta As ICollection(Of ExtractoRuta) = New HashSet(Of ExtractoRuta)
    
    End Class

End Namespace
