'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class SeguimientoCliente
        Public Property Empresa As String
        Public Property NºOrden As Integer
        Public Property Número As String
        Public Property Contacto As String
        Public Property Fecha As Date
        Public Property Tipo As String
        Public Property Vendedor As String
        Public Property Pedido As Boolean
        Public Property ClienteNuevo As Boolean
        Public Property Aviso As Boolean
        Public Property Aparatos As Boolean
        Public Property DatosBanco As Boolean
        Public Property GestiónAparatos As Boolean
        Public Property PrimeraVisita As Boolean
        Public Property Comentarios As String
        Public Property Estado As Short
        Public Property NumOrdenExtracto As Nullable(Of Integer)
        Public Property Cosmetica As Boolean
        Public Property PersonaQueDecide As Boolean
        Public Property PosibleVenta As Boolean
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property Clientes As Clientes
        Public Overridable Property Empresas As Empresas
        Public Overridable Property Vendedores As Vendedores
    
    End Class

End Namespace
