'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class SubGruposProducto
        Public Property Empresa As String
        Public Property Grupo As String
        Public Property Número As String
        Public Property Descripción As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property LinPedidoVta As ICollection(Of LinPedidoVta) = New HashSet(Of LinPedidoVta)
        Public Overridable Property Productos As ICollection(Of Productos) = New HashSet(Of Productos)
    
    End Class

End Namespace
