'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class Vendedores
        Public Property Empresa As String
        Public Property Número As String
        Public Property Descripción As String
        Public Property Estado As Short
        Public Property VendedorAnterior As String
        Public Property TipoComisión As String
        Public Property Mail As String
        Public Property Usuario As String
        Public Property Fecha_Modificación As Date
    
        Public Overridable Property CabFacturaVta As ICollection(Of CabFacturaVta) = New HashSet(Of CabFacturaVta)
        Public Overridable Property Vendedores1 As ICollection(Of Vendedores) = New HashSet(Of Vendedores)
        Public Overridable Property Vendedores2 As Vendedores
        Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
        Public Overridable Property Empresas As ICollection(Of Empresas) = New HashSet(Of Empresas)
        Public Overridable Property Empresas1 As Empresas
        Public Overridable Property ExtractoCliente As ICollection(Of ExtractoCliente) = New HashSet(Of ExtractoCliente)
        Public Overridable Property SeguimientoCliente As ICollection(Of SeguimientoCliente) = New HashSet(Of SeguimientoCliente)
        Public Overridable Property ExtractoRuta As ICollection(Of ExtractoRuta) = New HashSet(Of ExtractoRuta)
        Public Overridable Property EnviosAgencia As ICollection(Of EnviosAgencia) = New HashSet(Of EnviosAgencia)
        Public Overridable Property FamiliasVendedor As ICollection(Of FamiliasVendedor) = New HashSet(Of FamiliasVendedor)
    
    End Class

End Namespace
