'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class vstLinPedidoVtaComisiones
        Public Property Nº_Orden As Integer
        Public Property Empresa As String
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property Vendedor As String
        Public Property Ruta As String
        Public Property Nombre As String
        Public Property Dirección As String
        Public Property CodPostal As String
        Public Property Población As String
        Public Property Número As Integer
        Public Property Producto As String
        Public Property Texto As String
        Public Property Familia As String
        Public Property Fecha_Entrega As Date
        Public Property Cantidad As Nullable(Of Short)
        Public Property Estado As Short
        Public Property Picking As Nullable(Of Integer)
        Public Property Base_Imponible As Decimal
        Public Property Fecha_Albarán As Nullable(Of Date)
        Public Property Nº_Albarán As Nullable(Of Integer)
        Public Property Fecha_Factura As Nullable(Of Date)
        Public Property Nº_Factura As String
        Public Property Grupo As String
        Public Property SubGrupo As String
        Public Property EstadoFamilia As Nullable(Of Short)
        Public Property PrecioTarifa As Nullable(Of Decimal)
    
    End Class

End Namespace
