'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Nesto.Models

    Partial Public Class vstLinPedidoVtaConVendedor
        Public Property Nº_Orden As Integer
        Public Property Vendedor As String
        Public Property Ruta As String
        Public Property Nombre As String
        Public Property Dirección As String
        Public Property CodPostal As String
        Public Property Población As String
        Public Property Número As Integer
        Public Property Producto As String
        Public Property Texto As String
        Public Property Familia As String
        Public Property Fecha_Entrega As Date
        Public Property Cantidad As Nullable(Of Short)
        Public Property Estado As Short
        Public Property Picking As Nullable(Of Integer)
        Public Property Empresa As String
        Public Property Nº_Cliente As String
        Public Property Contacto As String
        Public Property Base_Imponible As Decimal
    
    End Class

End Namespace
